require:
  - rubocop-rspec

# These rules just don't align with how we write specs
RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/SpecFilePathSuffix:
  Enabled: false

# Maybe we're doing some unnecessary nesting, but it doesn't seem out of the ordinary for us to
# need a little more nesting. The default is 3. If we start wanting to bump it up higher than
# this, though, we may want to revisit what we're nesting for.
RSpec/NestedGroups:
  Max: 4
